# ConfigMap for app-two
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two-config
data:
  index.html: |
    <html>
      <head>
        <title>Welcome to App Two</title>
      </head>
      <body>
        <h1>Hello from App Two!</h1>
      </body>
    </html>

---

# Deployment for app-two
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: app-two
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-c-two
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html  # This allows to mount the file directly
      volumes:
      - name: html-volume
        configMap:
          name: app-two-config

---

# Service for app-two
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  selector:
    app: app-two
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
