# ConfigMap for app-three
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-three-config
data:
  index.html: |
    <html>
      <head>
        <title>Welcome to App Three</title>
      </head>
      <body>
        <h1>Hello from App Three!</h1>
      </body>
    </html>

---

# Deployment for app-three
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
  labels:
    app: app-three
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-c-three
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html  # This allows to mount the file directly
      volumes:
      - name: html-volume
        configMap:
          name: app-three-config

---

# Service for app-three
apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  selector:
    app: app-three
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
